src/Entity/Shop.php
<?php

namespace App\Entity;

use App\Repository\ShopRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopRepository::class)]
class Shop
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $Description = null;

    #[ORM\Column(length: 100)]
    private ?string $Address = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): static
    {
        $this->Address = $Address;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome Azer!{% endblock %}</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">
    <!--Style files -->
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    {% endblock %}
    <!--  js files-->
    <script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}" defer></script>
    {% block javascripts %}
        <script src="{{ asset('assets/js/script.js') }}" defer></script>
        {% block importmap %}{% endblock %}


    {% endblock %}
</head>
<body>
{% if app.user %}
    <div>
<<<<<<< HEAD
        <img src="{{ asset('/assets/images/' ~ app.user.Image) }}" alt="Profile Picture">
=======
        <img src="{{ asset('images/' ~ app.user.profilePicture) }}" alt="Profile Picture">
>>>>>>> 898a7f4140b3ff431eab9ad6a96c5767ab2d0a16
        Hello {{ app.user.Firstname }}!
    </div>
{% else %}
    <div>
        Welcome Guest!
    </div>
{% endif %}


{% block body %}{% endblock %}



</body>
</html>